[{"id":564929230,"node_id":"R_kgDOIawizg","name":"cve-2022-41352-zimbra-rce","full_name":"Cr4ckC4t/cve-2022-41352-zimbra-rce","private":false,"owner":{"login":"Cr4ckC4t","id":63863112,"node_id":"MDQ6VXNlcjYzODYzMTEy","avatar_url":"https://avatars.githubusercontent.com/u/63863112?v=4","url":"https://api.github.com/users/Cr4ckC4t","html_url":"https://github.com/Cr4ckC4t","type":"User","site_admin":false},"html_url":"https://github.com/Cr4ckC4t/cve-2022-41352-zimbra-rce","description":"Zimbra \u003c9.0.0.p27 RCE","fork":false,"url":"https://api.github.com/repos/Cr4ckC4t/cve-2022-41352-zimbra-rce","created_at":"2022-11-11T20:58:08Z","updated_at":"2022-11-21T07:58:09Z","pushed_at":"2022-11-14T17:54:57Z","stargazers_count":71,"watchers_count":71,"forks_count":14,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":["cpio","cve","cve-2022-41352","python3","rce","zimbra"],"visibility":"public","forks":14,"watchers":71,"default_branch":"main","score":1}]