[{"id":511432180,"node_id":"R_kgDOHnvV9A","name":"CVE-2022-34265","full_name":"aeyesec/CVE-2022-34265","private":false,"owner":{"login":"aeyesec","id":61375985,"node_id":"MDEyOk9yZ2FuaXphdGlvbjYxMzc1OTg1","avatar_url":"https://avatars.githubusercontent.com/u/61375985?v=4","url":"https://api.github.com/users/aeyesec","html_url":"https://github.com/aeyesec","type":"Organization","site_admin":false},"html_url":"https://github.com/aeyesec/CVE-2022-34265","description":"PoC for CVE-2022-34265 (Django)","fork":false,"url":"https://api.github.com/repos/aeyesec/CVE-2022-34265","created_at":"2022-07-07T07:45:28Z","updated_at":"2022-07-11T12:10:28Z","pushed_at":"2022-07-09T11:30:34Z","stargazers_count":70,"watchers_count":70,"forks_count":8,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":8,"watchers":70,"default_branch":"master","score":1},{"id":512737840,"node_id":"R_kgDOHo_CMA","name":"CVE-2022-34265","full_name":"NopFault/CVE-2022-34265","private":false,"owner":{"login":"NopFault","id":90475186,"node_id":"MDQ6VXNlcjkwNDc1MTg2","avatar_url":"https://avatars.githubusercontent.com/u/90475186?v=4","url":"https://api.github.com/users/NopFault","html_url":"https://github.com/NopFault","type":"User","site_admin":false},"html_url":"https://github.com/NopFault/CVE-2022-34265","description":"PoC verification of Django vulnerability (CVE-2022-34265)","fork":false,"url":"https://api.github.com/repos/NopFault/CVE-2022-34265","created_at":"2022-07-11T11:58:09Z","updated_at":"2022-07-11T12:08:16Z","pushed_at":"2022-07-11T12:01:20Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"master","score":1}]